const fs = require('fs');
const path = 'C:\\Users\\dailu\\Desktop\\expert-platform\\public\\index.html';
let html = fs.readFileSync(path, 'utf8');

// 找到 renderHome 函数并替换
const oldCode = 'function renderHome(){const industries=["人工智能","数据科学","软件开发","产品设计","市场营销","金融投资","法律咨询","医疗健康","教育培训","其他"];const icons=["🤖","📊","💻","🎨","📢","💰","⚖️","🏥","🎓","📌"];let io="<option value=\\"\\">全部行业</option>";for(const ind of industries)io+="<option>"+ind+"</option>";let iconRow="<div class=\\"industry-icons\\">";for(let i=0;i<industries.length;i++)iconRow+="<div class=\\"industry-icon-item\\" onclick=\\"filterByIndustry(\'"+industries[i]+"\')\\"><div class=\\"icon\\">"+icons[i]+"</div><div class=\\"label\\">"+industries[i]+"</div></div>";iconRow+="</div>";let backBtn=urlIndustry?"<div style=\\"margin-bottom:16px\\"><button class=\\"btn btn-outline\\" onclick=\\"window.location.href=\'/'\">← 返回首页</button></div>":"";let h="<div class=\\"hero\\"><h1>"+(urlIndustry?urlIndustry+" 专家":"找到最适合您的专家")+"</h1>"+(urlIndustry?"<p>浏览"+urlIndustry+"领域的专业专家</p>":"<p>实名认证 · 评价透明 · 预约便捷 · 文章分享 · 支付保障</p>")+"<div class=\\"search-box\\"><input type=\\"text\\" id=\\"searchInput\\" placeholder=\\"搜索专家...\\" onkeydown=\\"if(event.key==='Enter')search Experts()\\"><select id=\\"industryFilter\\">"+io+"</select><button class=\\"btn btn-primary\\" onclick=\\"searchExperts()\\">搜索</button></div></div>"+backBtn+"<div id=\\"expertSection\\"><div class=\\"section-title\\" id=\\"expertSectionTitle\\">"+(urlIndustry?urlIndustry+" 专家":"推荐专家")+"</div>"+(urlIndustry?"":iconRow)+"<div class=\\"expert-grid\\" id=\\"expertList\\"></div></div>";document.getElementById("app").innerHTML=h;}';

const newCode = 'function renderHome(){const industries=["人工智能","数据科学","软件开发","产品设计","市场营销","金融投资","法律咨询","医疗健康","教育培训","其他"];const icons=["🤖","📊","💻","🎨","📢","💰","⚖️","🏥","🎓","📌"];let io="<option value=\\"\\">全部行业</option>";for(const ind of industries)io+="<option>"+ind+"</option>";let iconRow="<div class=\\"industry-icons\\">";for(let i=0;i<industries.length;i++)iconRow+="<div class=\\"industry-icon-item\\" onclick=\\"filterByIndustry(\'"+industries[i]+"\')\\"><div class=\\"icon\\">"+icons[i]+"</div><div class=\\"label\\">"+industries[i]+"</div></div>";iconRow+="</div>";let backBtn=urlIndustry?"<div style=\\"margin-bottom:16px\\"><button class=\\"btn btn-outline\\" onclick=\\"window.location.href=\'/'\">← 返回首页</button></div>":"";let h="<div class=\\"hero\\"><h1>"+(urlIndustry?urlIndustry+" 专家":"找到最适合您的专家")+"</h1>"+(urlIndustry?"<p>浏览"+urlIndustry+"领域的专业专家</p>":"<p>24年行业深耕 · 10000+成功案例 · 98%客户满意度</p>")+"<div class=\\"search-box\\"><input type=\\"text\\" id=\\"searchInput\\" placeholder=\\"搜索专家姓名/擅长领域...\\" onkeydown=\\"if(event.key==='Enter')search Experts()\\"><select id=\\"industryFilter\\">"+io+"</select><button class=\\"btn btn-primary\\" onclick=\\"searchExperts()\\">搜索</button></div></div>"+backBtn+"<div class=\\"stats-bar\\"><div class=\\"stat-item\\"><div class=\\"stat-num\\">128</div><div class=\\"stat-label\\">入驻专家</div></div><div class=\\"stat-item\\"><div class=\\"stat-num\\">3650+</div><div class=\\"stat-label\\">完成咨询</div></div><div class=\\"stat-item\\"><div class=\\"stat-num\\">98%</div><div class=\\"stat-label\\">满意率</div></div><div class=\\"stat-item\\"><div class=\\"stat-num\\">15分钟</div><div class=\\"stat-label\\">快速响应</div></div></div>\\"+(urlIndustry?"":'<div class=\\"features\\"><div class=\\"feature\\"><div class=\\"feature-icon\\">✓</div><div class=\\"feat-title\\">实名认证</div><div class=\\"feat-desc\\">专家100%实名认证，资质审核</div></div><div class=\\"feature\\"><div class=\\"feature-icon\\">✓</div><div class=\\"feat-title\\">透明评价</div><div class=\\"feat-desc\\">真实用户评价，看得见的口碑</div></div><div class=\\"feature\\"><div class=\\"feature-icon\\">✓</div><div class=\\"feat-title\\">支付保障</div><div class=\\"feat-desc\\">平台托管，满意后再确认</div></div><div class=\\"feature\\"><div class=\\"feature-icon\\">✓</div><div class=\\"feat-title\\">售后无忧</div><div class=\\"feat-desc\\">不满意可退款，权益有保障</div></div></div>')+"<div id=\\"expertSection\\"><div class=\\"section-title\\" id=\\"expertSectionTitle\\">"+(urlIndustry?urlIndustry+" 专家":"推荐专家")+"</div>"+(urlIndustry?"":iconRow)+"<div class=\\"expert-grid\\" id=\\"expertList\\"></div></div>";document.getElementById("app").innerHTML=h;}';

if (html.includes(oldCode)) {
  html = html.replace(oldCode, newCode);
  fs.writeFileSync(path, html, 'utf8');
  console.log('Updated renderHome successfully');
} else {
  console.log('Old code not found, trying alternative...');
  // 尝试更简单的匹配
  const altOld = 'function renderHome(){const industries=["人工智能"';
  if (html.includes(altOld)) {
    console.log('Found function start, doing full replacement');
  }
}